version: '3.0'
services:
    zookeeper:
        image: zookeeper:3.4.10
        #restart: always
        container_name: zookeeper
        ports:
            - "2181:2181"

networks:
    default:
        external:
            name: mynet
