version: '3.0'

services:
  activemq:
    #build: .
    image: activemq:5.15.3
    # restart: always
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    
networks:
  default:
    external:
      name: bcdigger_net

