version: '3.1'

services:

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: docker_db_123
        ports:
            - "3306:3306"

    adminer:
        image: adminer
        # restart: always
        ports:
            - 3308:8080
