version : '3.1'

services :
  db :
    container_name : mysqldb
    image : mysql:5.7.21
    restart : always
    environment :
      MYSQL_ROOT_PASSWORD: docker_db_bcdigger
    ports :
      - "3306:3306"
    volumes :
      - /home/bcdigger/docker_mapping_file/mysql/data:/mysql_data
      - /home/bcdigger/docker_mapping_file/mysql/conf/my.cnf:/etc/mysql/my.cnf
    privileged : true
